# Libraries
library(knitr)
library(stringr)
library(janitor)
library(kableExtra)
library(tidyr)
library(tibble)
library(ggplot2)
library(ggbeeswarm)
library(RColorBrewer)
library(colorRamps)
library(lubridate)
library(scales)
library(gghighlight)
library(rlang)
library(ggthemes)
library(readr) # aca actualizar
# library(tidyquant)
library(tibbletime)
library(formattable)
library(jsonlite)
library(skimr)
#library(cvequality)
library(corrplot)
library(moments)
library(htmltools)
#library(DataExplorer)
#library(matlib)
library(MASS)
library(broom)
library(FactoMineR)#  
library(factoextra)
library(vcd)
library(gplots)
library(nortest)
library(reshape2)
library(MVN)
library(klaR)
library(biotools)
library(e1071)
library(caret)
library(readxl)
library(cluster)
library(kableExtra)
library(raster)
library(dplyr)
library(data.table)

