pacman::p_load(car)
data(Duncan)
fitLS <- lm(income  ~ education, data = Duncan )
library(jtools) 
jtools::summ(fitLS)
summary(fitLS)
autoReg::autoReg(fitLS)
library(datarium)
data(marketing)
str(marketing)
